# Generated by Django 3.2.18 on 2023-02-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('do_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_menu.menu')),
            ],
        ),
    ]
