# Generated by Django 3.2.18 on 2023-02-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('do_menu', '0002_listmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='do_menu.menu'),
        ),
        migrations.DeleteModel(
            name='ListMenu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
