# Generated by Django 3.2.18 on 2023-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_menu', '0004_auto_20230225_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(),
        ),
    ]
